version: 2.1

setup: true

orbs:
  python: circleci/python@2.0.3
  gcp-cli: circleci/gcp-cli@3.3.0
  gcp-storage: freighthub/gcp-storage@0.1
  cli: circleci/circleci-cli@0.1.9
  git-shallow-clone: guitarrapc/git-shallow-clone@2.8.0


jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - run: mkdir -p workspace
      - python/install-packages:
          pkg-manager: pip
      - python/install-packages:
          pip-dependency-file: requirements.txt
          pkg-manager: pip
      - python/install-packages:
          args: pytest
          pkg-manager: pip
          pypi-cache: false
      - run: printenv
      - run:
          command: |
            python3 p1.py     
      - run:
          command: |
            pytest --version
          name: Test
      - run:
          name: Show all files
          command: find "$(pwd)"
      - persist_to_workspace:
          root: workspace
          paths: 
            - .

  use-gcp:
    executor: gcp-cli/default
    steps:
      - gcp-cli/setup:
          version: 404.0.0      
      - run: 
          name: Setup Google Cloud SDK
          command: |
            echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
      - attach_workspace:
           at: workspace
           path:
           - .
      - gcp-storage/upload:
            source_path: Repos
            destination_bucket: backup_folder
            cache_control: public, max-age=86400

workflows:
  main:
    jobs:
      - build
      - use-gcp