version: 2.1

orbs:
  aws-s3: circleci/aws-s3@3.0.0 # Do not bump unless you made sure the benchmark upload still works
  gcp-cli: circleci/gcp-cli@3.3.0
  git-shallow-clone: guitarrapc/git-shallow-clone@2.8.0
  python: circleci/python@2.1.1

parameters:
  version:
    type: string
    default: 6.1.3 # edited by pipeline
  base_branch:
    type: string
    default: "6.1"

executors:
  deploy-docker:
    docker:
      - image: cimg/deploy:2024.08.1-node

  vm:
    machine: # https://www.testcontainers.org/supported_docker_environment/continuous_integration/circle_ci/
      image: ubuntu-2204:2024.04.4

  base:
    docker:
      - image: cimg/base:current

commands:
    setup_directquery_cloud_credentials:
    steps:
      - run:
          name: Write DirectQuery Cloud Credentials to a file
          command: |
            mkdir -p $HOME/{.aws,.google}
            echo $DIRECTQUERY_AWS_CREDENTIALS | base64 --d > $HOME/.aws/direct-query-credentials
            echo $DIRECTQUERY_GCP_CREDENTIALS | base64 --d > $HOME/.google/direct-query-credentials

  save_git_hash_for_cli:
    steps:
      - run:
          name: Identify last changes in CLI for caching
          command: |
            CHECKSUM_CLI_SOURCE="$(find cli/src -type f -print0 |
              # Sorted for consistent order
              sort -z |
              # checksum for each file
              xargs -0 sha1sum |
              # checksum of all checksums
              sha1sum |
              # only return the checksum
              cut -d ' ' -f 1)"
            echo "$CHECKSUM_CLI_SOURCE" | tee /tmp/atoti_javascript_cli.custom_lock

    shallow_checkout:
    steps:
      - git-shallow-clone/checkout:
          no_tags: true

  install_ssh_credentials_artifacts_server:
    description: Install credentials for server artifacts
    steps:
      - run:
          name: Install SSH configuration for artifacts server
          command: |
            mkdir -p ~/.ssh
            echo "Host ${ARTIFACTS_URL}" >> ~/.ssh/config
            echo "  Hostname ${ARTIFACTS_URL}" >> ~/.ssh/config
            echo "  User ${ARTIFACTS_USER}" >> ~/.ssh/config
            echo "  Port ${ARTIFACTS_PORT}" >> ~/.ssh/config
            echo "  BatchMode yes" >> ~/.ssh/config
            echo "  HostKeyAlgorithms +ssh-rsa" >> ~/.ssh/config
            echo "  PubkeyAcceptedAlgorithms +ssh-rsa" >> ~/.ssh/config
      - run:
          name: Recognize server fingerprint for security
          command: echo "${ARTIFACTS_FINGERPRINT}" >> ~/.ssh/known_hosts

  install_ssh_credentials_github:
    description: Install credentials for Github
    steps:
      - run:
          name: Add Github public key to known hosts
          command: |
            mkdir -p ~/.ssh
            ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
      - add_ssh_keys:
          fingerprints:
            - "e9:46:96:f7:9c:24:a3:ba:42:3c:e4:46:91:86:4b:01"
